version: '3.9'
services:
  sidekiq:
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml
    depends_on:
      - redis
    env_file:
      - .env
    working_dir: /desafio-backend
    volumes:
      - .:/desafio-backend

  redis:
    container_name: redis
    image: redis:6.2
    command: redis-server --port 7479
    ports:
      - "7479:7479"

  db:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
  web:
    stdin_open: true
    tty: true
    container_name: desafio-backend
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/desafio-backend
    ports:
      - "3000:3000"
    depends_on:
      - db
      - sidekiq
    env_file:
      - .env

