
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: desafio_backend_development
  host: localhost
  username: postgres
  password: postgres

test:
  <<: *default
  host: localhost
  database: desafio_backend_test
  username: postgres
  password: postgres